DROP TABLE PTKTPopusti;
CREATE TABLE PTKTPopusti ( ID INT NOT NULL , KartaID INT NOT NULL, VeljaOd DATETIME NOT NULL, VrstaPopustaID INT NOT NULL, NacinIzracuna INT, Popust FLOAT(53), CONSTRAINT PK_PTKTPopusti PRIMARY KEY (ID) );
CREATE UNIQUE INDEX IX_PTKTPopusti ON PTKTPopusti (KartaID, VeljaOd);
